# Generated by Django 5.2.7 on 2025-10-02 03:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de verificación'), ('verified', 'Verificado y participando'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inscripción')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de verificación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'db_table': 'participants',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draw_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del sorteo')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de notificación')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Notificado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Ganador',
                'verbose_name_plural': 'Ganadores',
                'db_table': 'winners',
                'ordering': ['-draw_date'],
            },
        ),
    ]
