# Generated by Django 5.2.7 on 2025-10-02 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='winner',
            name='drawn_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draws_performed', to=settings.AUTH_USER_MODEL, verbose_name='Sorteado por'),
        ),
        migrations.AddField(
            model_name='winner',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='contest.participant'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['status', 'verified_at'], name='participant_status_8404bc_idx'),
        ),
    ]
